### ISSUE TITLE
QueryToInt64 works strange

### ISSUE THREAD

**Issue by winogradoff** [elgs/gojq#1]
It works strange:

**_func (jq *JQ) QueryToInt64(exp string) (int64, error)**_

This code:

``` go
json := `{"response":[{"uid":123456789}]}`
parser, _ := gojq.NewStringQuery(json)
uid, err := parser.QueryToInt64("response.[0].uid")

if err != nil {
    fmt.Println("ERROR")
}
fmt.Println(uid)
```

returns the following:

```
ERROR
0
```

Probably interface is float64 in this case.

**Comment by elgs** [comment]
Thank you @winogradoff for fixing this issue.
