### ISSUE TITLE
Recent change to elgs/gosplitargs breaks this module

### ISSUE THREAD

**Issue by bceschi** [elgs/gojq#5]
Just wanted to let you know that the recent (Mar 10) commit to `elgs/gosplitargs` has broken this module.

With "github.com/elgs/gosplitargs v0.0.0-20230310130726-7d16e488436a // indirect" Tests fail.

```
$ go test github.com/elgs/gojq
--- FAIL: TestParseJsonArray (0.00s)
    gojq_test.go:65: [0].name is not an object. map[]
    gojq_test.go:68: Expected: elgs actual: <nil>
    gojq_test.go:65: [1].gender is not an object. map[]
    gojq_test.go:68: Expected: f actual: <nil>
    gojq_test.go:65: strconv.Atoi: parsing "2].skills.[1": invalid syntax
    gojq_test.go:68: Expected: Sleeping actual: <nil>
    gojq_test.go:65: [2].hello is not an object. map[]
    gojq_test.go:65: [2].hello.world is not an object. map[]
    gojq_test.go:68: Expected: true actual: <nil>
--- FAIL: TestParseJsonObj (0.00s)
    gojq_test.go:112: skills.[1] does not exist.
    gojq_test.go:115: Expected: Sleeping actual: <nil>
FAIL
FAIL    github.com/elgs/gojq    0.002s
FAIL
```

Rollback to "github.com/elgs/gosplitargs v0.0.0-20151006035528-91e4283ea52d // indirect" and the tests pass.
```
vscode@15555a6ce6c2:/workspaces/post_cr_gmdb$ go test github.com/elgs/gojq
ok      github.com/elgs/gojq    0.002s
```

I may try to fix `elgs/gosplitargs` and create a Pull request, but figured you might want to know.

Thanks for the useful modules!

**Comment by elgs** [comment]
Thank you. Checking it.

**Comment by elgs** [comment]
It should have been fixed. Can you please help to try again? Thanks.

**Comment by bceschi** [comment]
Works over here. You want to close the issue or should I?
Thanks!

**Comment by elgs** [comment]
Thank you for confirming it. Closing now.
